# Snuggles config!
# This is not a config for servers, but for the bot itself; you should only worry about this if you're self-hosting.
#
# Incase you mess up bad, you can find the original config for reference here:
# https://github.com/UwUAroze/Snuggles/tree/v2/src/main/resources/config.toml
# Alternatively you can just delete this file and restart the bot, generating a new one for you.

[authentication]
token = "Discord bot token"
mongo = "mongodb://localhost:27017"

[bot]
invite_link = "https://discord.com/api/oauth2/authorize?client_id=0000000000000000000&permissions=140123688001&scope=bot%20applications.commands"